// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/frame-go-sdk/pkg/models/shared"
	"net/http"
)

type GetAccountRequest struct {
	AccountID int64 `pathParam:"style=simple,explode=false,name=account_id"`
}

type GetAccountResponse struct {
	// Account information retrieved successfully
	Account     *shared.Account
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
