// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/frame-go-sdk/pkg/models/shared"
	"net/http"
)

type GetUserInfoResponse struct {
	ContentType string
	// Not Authorized
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// User information retrieved successfully
	User *shared.User
}
