// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Account - Account information retrieved successfully
type Account struct {
	AccountID *string `json:"account_id,omitempty"`
	Email     *string `json:"email,omitempty"`
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
}
