// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ErrorErrors struct {
	Code   *int64  `json:"code,omitempty"`
	Detail *string `json:"detail,omitempty"`
	Status *int64  `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// Error - Not Authorized
type Error struct {
	Code    *int64        `json:"code,omitempty"`
	Errors  []ErrorErrors `json:"errors,omitempty"`
	Message *string       `json:"message,omitempty"`
}
