// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// User - User information retrieved successfully
type User struct {
	AccountID *string `json:"account_id,omitempty"`
	Email     *string `json:"email,omitempty"`
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
}
